[package]
name = "rusteddrawer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
glib = "0.18.2"
kbar = "0.1.3"
rodio = "0.16.0"
clap = { version = "4.1.4", features = ["derive"] }
